---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: namespace-allowance-admission-webhook
webhooks:
  - name: namespace-allowance.example.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Ignore
    clientConfig:
      url: ${URL}
      caBundle: ${CA_BUNDLE_BASE64}
